[package]
name = "rust-tokenizer"
version = "0.1.0"
authors = ["Javad Asgari Shafique <javadshafique@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
